Issue/14 inputs validation
FoodStandardsAgency/data-dot-food-editor pull request #9
Opened 2020-10-21 16:06 UTC by bogdanadrianmarc

This PR is related to issue: https://github.com/FoodStandardsAgency/data-dot-food/issues/14 . After checking all the app's inputs, validation was only missing for the login page ones; this PR adds that and a change to make the element requirement more visible. Some general fields are still not being validated since there are existing datasets that have those fields empty, so imposing requirements on those can possibly prevent the addition of some datasets in the future

2020-10-22 06:40 UTC, joescottdave requested changes
Some changes needed to the CSS here.

2020-10-22 06:40 UTC, joescottdave commented on src/Login.vue
> +  span {
This is far too general a selector, particularly as the rule fundamentally changes the anticipated layout behaviour of a `span` from `inline` to `block`, and is not contained within a scoped CSS block.

Suggest creating a new class name for span elements that require this treatment, or wrapping them in a `div`

2020-10-22 06:40 UTC, joescottdave commented on src/Login.vue
> +  label {
Ditto above. This would I think set a global rule for all labels, should add a class

2020-10-22 06:47 UTC, ijdickinson commented on src/Login.vue
> +  span {
I agree.

2020-10-27 18:53 UTC, bogdanadrianmarc commented on src/Login.vue
> +  span {
Agree as well, I don't know why I haven't thought about this from the beginning 🦆 . I fixed this using classes but also scoped the css, since everything in there is used exclusively for the login page

2020-10-28 08:33 UTC, ijdickinson reviewed
Suggested a further small simplification

2020-10-28 08:33 UTC, ijdickinson commented on src/Login.vue
> +  .validation-errors {
Rather than have a `span` with `display: block`, why not just make the element a `div`? Keep it simple :smile:

2020-11-02 10:52 UTC, ijdickinson approved these changes
lgtm

2020-11-03 09:11 UTC, joescottdave approved these changes
👍

2020-11-05 11:48 UTC, merged